title: Worcester Auto
email: worcesterautoparts@gmail.com
description: >- 
  Here at worcester auto, we do our best to serve customers with respect, and fair prices. The owner of worcester auto would love to meet you!
baseurl: "" 
url: "" 
github_username:  quicktest0532

# Build settings
markdown: kramdown
theme: hacker
plugins:
  - jekyll-feed
